=== BackupTheBerlios/jrframework/demo-db4o/src/app.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : app.dtd
    Created on : 6 de febrero de 2005, 17:29
    Author     : jose
    Description:
        Purpose of the document follows.

    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/app.dtd
-->

<!ELEMENT Aplicacion  (Doc?,Help?,CasoUso)+ > <!--Doc/help-->
<!ELEMENT CasoUso     (Ventana)+ > <!--Doc/help-->
<!ELEMENT Ventana     (Bean*,Panel,Operacion+) > <!--Doc/help-->
<!ELEMENT Panel       (Panel*,Propiedad*)* > <!--Doc/help-->
<!ELEMENT Operacion   (Opcion*,Propiedad*)+ > <!--Doc/help-->
<!ELEMENT Bean        (Propiedad)* > <!--Doc/help-->
<!ELEMENT Opcion      EMPTY>  <!--Doc/help-->
<!ELEMENT Propiedad   EMPTY>
<!ELEMENT Doc         (#PCDATA) >
<!ELEMENT Help        (#PCDATA) >

<!ATTLIST Aplicacion  
    nombre CDATA #REQUIRED>
<!ATTLIST CasoUso     
    id CDATA #REQUIRED
    init CDATA #REQUIRED>
<!ATTLIST Ventana     
    id CDATA #REQUIRED>
<!ATTLIST Bean        
    name CDATA #REQUIRED
    className CDATA #REQUIRED>
<!ATTLIST Panel       
    className CDATA #REQUIRED>
<!ATTLIST Propiedad   
    name CDATA #REQUIRED
    value CDATA #REQUIRED>
<!ATTLIST Operacion   
    nombre CDATA #REQUIRED
    beanName CDATA #IMPLIED
    activacion CDATA #IMPLIED
    tooltip CDATA #IMPLIED
    visible CDATA #IMPLIED
    aviso   CDATA #IMPLIED 
    icon   CDATA #IMPLIED
    label   CDATA #IMPLIED
    metodo   CDATA #IMPLIED
    >

<!ATTLIST Opcion        
    res     CDATA #IMPLIED
    dest    CDATA #REQUIRED
    >

=== BackupTheBerlios/jrframework/demo-db4o/src/app.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : app.xml
    Created on : 6 de febrero de 2005, 17:31
    Author     : jose
    Description:
        Purpose of the document follows.
-->

<!DOCTYPE app PUBLIC '-//Sun Microsystems Inc.//DTD Application Server 8.0 Domain//EN' 'app.dtd'>

<Aplicacion nombre="Nueva Aplicacion">
<CasoUso id="CasoUso001" init="ListaEntidades" >
    <Ventana id="ListaEntidades">
        <Panel className="com.application.widgets.SplitPane">
            <Panel className="com.application.widgets.PanelBuscarUno"/>
            <Panel className="com.application.widgets.TableBean">
               <Propiedad name="varSelected" value="UnValor"/>
            </Panel>   
        </Panel>    
        <Operaciones>
            <Operacion 
                nombre="Buscar Estaciones" 
                label="Buscar Estaciones" 
                icon="tasks_tsk.gif"
                aviso="Â¿Quieres obtener las subestaciones?"
                className="metro.servicios.BeanFinder" >
                  <Opcion res="OK" dest="main2" />
                  <Opcion res="Fallo" dest="xxxx" />
                  <Propiedad name="bean" value="metro.model.Estacion"/>
            </Operacion>
            <Operacion 
                nombre="Buscar Vestibulos" 
                label="Buscar Vestibulo" 
                icon="tasks_tsk.gif"
                className="metro.servicios.BeanFinder" >
                  <Opcion res="OK" dest="main2" />
                  <Opcion res="Fallo" dest="xxxx" />
                  <Propiedad name="bean" value="metro.model.Vestibulo"/>
            </Operacion>
            <Operacion 
                nombre="Buscar Maquinas" 
                label="Buscar Maquina" 
                icon="tasks_tsk.gif"
                visible="no"
                className="metro.servicios.BeanFinder" >
                  <Opcion res="OK" dest="main2" />
                  <Opcion res="Fallo" dest="xxxx" />
                  <Propiedad name="bean" value="metro.model.Maquina"/>
            </Operacion>
            <Operacion 
                nombre="Detalle Seleccionados" 
                label="Buscar Maquina" 
                visible="UnValor"
                icon="tasks_tsk.gif">
                  <Opcion dest="UnaEntidad" />                  
            </Operacion>
        </Operaciones>
    </Ventana>    
    
    <Ventana id="UnaEntidad">
        <Panel className="com.application.widgets.PanelBeanForm"/>

        <Operaciones>
            <Operacion 
                nombre="Vuelta Lista" 
                label="Buscar Maquina" 
                icon="tasks_tsk.gif">
                  <Opcion dest="FIRST" />                  
            </Operacion>

        </Operaciones>
     </Ventana>       
</CasoUso>

</Aplicacion>

=== BackupTheBerlios/jrframework/demo-db4o/src/app2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--
    Document   : app.xml
    Created on : 6 de febrero de 2005, 17:31
    Author     : jose
    Description:
        Purpose of the document follows.
-->

<!DOCTYPE Aplicacion PUBLIC '-//Sun Microsystems Inc.//DTD Application Server 8.0 Domain//EN' 'app.dtd'>



<Aplicacion nombre="Aplicacion de Prueba">
    <CasoUso id="CasoUso001" init="ListaEntidades">
        <Ventana id="ListaEntidades">        
            <Bean name="Buscador" className="metro.servicios.BeanFinder" />
            <Panel  className="com.application.widgets.SplitPane" >
                <Panel  className="com.application.widgets.PanelBuscarUno" ></Panel>
                <Panel  className="com.application.widgets.TableBean" >
                    <Propiedad name="variable" value="Clientes" />
                    <Propiedad name="varSelected" value="UnValor" />
                </Panel>
            </Panel>
            <Operacion nombre="INIT" beanName="Buscador" activacion="init" >  
                <Propiedad name="bean" value="metro.model.Estacion" />
             </Operacion>
            <Operacion nombre="Buscar Estaciones" beanName="Buscador"
                tooltip="Busca todas las subestaciones" >  
                <Propiedad name="bean" value="metro.model.Estacion" />
                </Operacion>
            <Operacion nombre="Buscar Vestibulos" beanName="Buscador" 
                tooltip="Busca todas los vestibulos">
                <Propiedad name="bean" value="metro.model.Vestibulo" />
            </Operacion>
            <Operacion nombre="Buscar Maquinas" beanName="Buscador"
                tooltip="Busca todas las Maquinas" >
                <Propiedad name="bean" value="metro.model.Maquina" />
            </Operacion>
            <Operacion nombre="Detalle Seleccionados" 
                visible="UnValor"
                aviso="Seguro?"
                >
                <Opcion dest="UnaEntidad" />
            </Operacion>
        </Ventana>
        <Ventana id="UnaEntidad">
            <Panel  className="com.application.widgets.PanelBeanForm" >
                <Propiedad name="variable" value="unValor" />
            </Panel>
            <Operacion nombre="Vuelta Lista" >
                <Opcion dest="BACK" />
            </Operacion>
        </Ventana>
    </CasoUso>
</Aplicacion>
